version: '3.9'
services:
  db:
    container_name: db
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - ./data/dev/mongo:/data/db

  app:
    build: .
    container_name: app
    environment:
      - SERVICE_NAME=nba_simulator
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=3000
      - MONGO_HOSTNAME=db
      - MONGO_PORT=27017
      - DATABASE_NAME=nba_simulator
    ports:
      - 3000:3000
    depends_on:
      - db
